DROP INDEX ix_audit_actor ON audit_log;
ALTER TABLE audit_log DROP FOREIGN KEY fk_audit_actor_user;
ALTER TABLE audit_log DROP COLUMN actor_email;
ALTER TABLE audit_log DROP COLUMN actor_user_id;
DROP TABLE auth_setting;
DROP TABLE auth_device_sync;
DROP INDEX ix_auth_session_user ON auth_session;
DROP TABLE auth_session;
DROP TABLE auth_login_challenge;
DROP TABLE auth_user;
